### ISSUE TITLE
Fail to build with Sphinx > 1.6.0

### ISSUE THREAD

**Issue by jd** [Robpol86/sphinxcontrib-versioning#56]
Commit e8e63b1e9968abbaff46ddd7917d2b53cb505276 in Sphinx removed `sphinx.builders.html.StandaloneHTMLBuilder.default_sidebars` so build now fails with:

```
Exception occurred:
  File "/Users/jd/Source/gnocchi/.tox/docs-gnocchi.xyz/lib/python2.7/site-packages/sphinxcontrib/versioning/sphinx_.py", line 60, in builder_inited
    app.config.html_sidebars['**'] = StandaloneHTMLBuilder.default_sidebars + ['versions.html']
AttributeError: type object 'StandaloneHTMLBuilder' has no attribute 'default_sidebars'
```

**Comment by paddy-hack** [comment]
This can be fixed by applying #46 or #50
