### PR TITLE
dereference deprecated default_sidebars

### LINKED ISSUE #39: Sphinx 1.6.1 compatibility
Yesterday, on May 16th, sphinx 1.6.1 was released. sphixcontrib-versioning does not work with that version of sphinx, since the ``StandaloneHTMLBuilder`` does not have the ``default_sidebars`` attribute anymore, so it fails on ``AttributeError``:

```
=> Pre-running Sphinx to collect versions' master_doc and other info.
Running Sphinx v1.6.1
loading translations [cs]... done
loading pickled environment... not yet created

Exception occurred:
  File "/home/zegklitz/sandbox/sphinxversioning-env/lib/python3.5/site-packages/sphinxcontrib/versioning/sphinx_.py", line 60, in builder_inited
    app.config.html_sidebars['**'] = StandaloneHTMLBuilder.default_sidebars + ['versions.html']
AttributeError: type object 'StandaloneHTMLBuilder' has no attribute 'default_sidebars'
The full traceback has been saved in /tmp/sphinx-err-hnfq1qko.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zegklitz/sandbox/sphinxversioning-env/lib/python3.5/site-packages/sphinxcontrib/versioning/sphinx_.py", line 204, in _build
    raise SphinxError
sphinx.errors.SphinxError
=> sphinx-build failed for branch/tag: feature/sdgraph2
Failure.
```

There are probably more things that went off-rails, this is just the first one that comes up. It works with sphinx 1.5.6 just fine.

The best option would be to make it compatible with 1.6.1. But, fixing it or not, it would be wise to indicate with which sphinx versions does sphinxcontrib-versioning work. It took me quite a lot of digging in the sphinx files and changelogs until I found the source of the issue.

### PR DESCRIPTION
**Pull request by Lingnik**
StandaloneHTMLBuilder.default_sidebars was removed in sphinx ~1.6.

https://github.com/sphinx-doc/sphinx/commit/e8e63b1e9968abbaff46ddd7917d2b53cb505276#diff-c17608ed63bfe1714c6befb9d4201fee

Fixes #39

### CODE REVIEW

**Comment by Lingnik** [comment]
@Robpol86 I can't grok how so many more tests in appveyor began failing with this change, and they seem unrelated to what I did. Also don't understand the coverage decrease for files other than sphinx_.py. Assigning to you anyways for merge?

**Comment by Levi-Armstrong** [comment]
:+1:  @Lingnik Thank you for the fix. I installed your branch and everything worked as expected.

**Comment by FraBle** [comment]
@Robpol86, please merge this PR :)

**Comment by FraBle** [comment]
@Robpol86, any updates on this PR?

**Comment by tmbo** [comment]
@Robpol86 mind merging this one? If you don't maintain the repository anymore - please let someone else (e.g. one of the already existing contributors) take over.

**Comment by mortenvp** [comment]
@Robpol86 also affected by this one - please merge

**Comment by sizmailov** [comment]
to install patched version
```bash
pip install -U git+https://github.com/Lingnik/sphinxcontrib-versioning@Lingnik-patch-1
```

**Comment by zhanghang1989** [comment]
Hi guys, is `sphinx-versioning` reinstalling/using the package in different commit? It seems that it only uses the master branch version. Therefore, the doc building often fails. Any comments? Thanks!

**Comment by sizmailov** [comment]
@zhanghang1989, `sphinx-versioning` checks out different commits, but does not perform install. If you have pure python project that should be enough to build documentation correctly. 

In my project I have C++-extension module, so I need install to properly generate module API with autodoc. 
I added several options to `sphinx-versioning` to actually trigger `python setup.py install` during doc generation, try the fork:
```bash
pip install -U git+https://github.com/sizmailov/sphinxcontrib-versioning@conditionally_run_setup_py
```

**Comment by ashb** [comment]
This change seems to remove entirely the default sidebars for me - I just end up with the versions in the side bar, but when building standalone I get a TOC and a few others.
